"""
Full end-to-end re-verification of the entire corpus. Three layers:

  A. Every witness file: brute-force validity check (independent checker).
  B. Every certificate CNF: regenerated by an INDEPENDENT generator (written
     differently from rado_core.clauses_for) and compared clause-by-clause,
     so the DRAT proof is guaranteed to be about the right formula.
  C. Every DRAT proof: re-verified with drat-trim.

Exit summary lists any failure explicitly.
"""
import json
import multiprocessing as mp
import re
import subprocess
import time
from pathlib import Path

from check_witness import check
from certify import DRATTRIM

BASE = Path(__file__).parent


def independent_clauses(a, c, N):
    """Deliberately naive regeneration: full double loop, no derived bounds."""
    cls = set()
    for x1 in range(1, N + 1):
        for x2 in range(1, N + 1):
            x3 = x1 + a * x2 - c
            if 1 <= x3 <= N:
                lits = tuple(sorted({x1, x2, x3}))
                cls.add(lits)
                cls.add(tuple(sorted(-v for v in lits)))
    return cls


def parse_dimacs(path):
    cls = set()
    for line in open(path, encoding="utf-8"):
        line = line.strip()
        if not line or line[0] in "cp":
            continue
        lits = tuple(sorted(int(t) for t in line.split()[:-1]))
        cls.add(lits)
    return cls


def check_witness_file(path):
    d = json.load(open(path, encoding="utf-8"))
    bad = check(d["a"], d["c"], d["coloring"])
    ok = bad is None and len(d["coloring"]) == d["rad2"] - 1
    return (str(path.name), ok)


CERT_RE = re.compile(r"rado_a(-?\d+)_c(-?\d+)_N(\d+)\.cnf$")


def check_certificate(cnf_path):
    m = CERT_RE.search(cnf_path.name)
    a, c, N = int(m.group(1)), int(m.group(2)), int(m.group(3))
    # B: independent CNF regeneration
    if parse_dimacs(cnf_path) != independent_clauses(a, c, N):
        return (cnf_path.name, "CNF-MISMATCH")
    # C: drat-trim
    proof = cnf_path.with_suffix(".drat")
    if not proof.exists():
        return (cnf_path.name, "NO-PROOF")
    r = subprocess.run([str(DRATTRIM), str(cnf_path), str(proof)],
                       capture_output=True, text=True, timeout=3600)
    if "s VERIFIED" not in r.stdout:
        return (cnf_path.name, "DRAT-FAIL")
    return (cnf_path.name, "OK")


if __name__ == "__main__":
    t0 = time.time()
    wits = sorted((BASE / "witnesses").glob("*.json"))
    certs = sorted((BASE / "certificates").glob("*.cnf"))
    print(f"{len(wits)} witnesses, {len(certs)} certificates", flush=True)

    with mp.Pool(10) as pool:
        wres = pool.map(check_witness_file, wits, chunksize=16)
        bad_w = [n for n, ok in wres if not ok]
        print(f"[A] witnesses OK: {len(wres)-len(bad_w)}/{len(wres)}"
              + (f"  FAILURES: {bad_w[:10]}" if bad_w else ""), flush=True)

        cres = pool.map(check_certificate, certs, chunksize=4)
        bad_c = [(n, s) for n, s in cres if s != "OK"]
        print(f"[B+C] certificates OK: {len(cres)-len(bad_c)}/{len(cres)}"
              + (f"  FAILURES: {bad_c[:10]}" if bad_c else ""), flush=True)

    verdict = "TOT VERIFICAT" if not bad_w and not bad_c else "HI HA FALLADES"
    print(f"{verdict} en {time.time()-t0:.0f}s", flush=True)
